name: Build APK

on:
  push:
    branches: [main, experimental]
  pull_request:
    branches: [main, experimental]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Haxe
        run: |
          sudo apt-get update
          sudo apt-get install -y haxe
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl

      - name: Install Haxelib Dependencies
        run: |
          for i in {1..3}; do
            haxelib install lime && haxelib install openfl && break || sleep 10
          done

      # Install HMM without cloning the GitHub repo
      - name: Install HMM (Haxe Module Manager)
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Build Android APK
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id }}"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: export/release/android/bin

      - name: Cleanup Artifacts
        run: |
          find export/release/android/bin -type f -name "*.apk" -mtime +1 -exec rm -f {} \;