name: Build APK

on:
  push:
    branches: [main, experimental]
  pull_request:
    branches: [main, experimental]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlccore-dev -y
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install hxcpp
          haxelib install tjson
          haxelib install hxCodec
          haxelib install SScript
          haxelib install hxcpp-debug-server
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib install extension-android-tools
          haxelib install extension-vibrate

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Build APK
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id }}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: androidBuild
          path: 'export/release/android/bin'
